### ISSUE TITLE
Provide separate factory methods for SystemFontMetrics and IndexedFontMetrics

### ISSUE THREAD

**Issue by obecker** [ggrandes/fontmetrics#1]
Hi, it would be great if the `SimpleFontMetrics` API could be extended to select specifically either the `SystemFontMetrics` or the `IndexedFontMetrics` implementation (actually - for my use case it would be enough to have access to the `IndexedFontMetrics`).

Background: I'm using this library for creating SVG images and have some tests that contain assertions for the entire generated markup. To my surprise these tests failed when executed automatically within GitHub Actions (I guess this might be a problem in general on CI environments). The cause were slightly different values returned from the fontmetrics library. Apparently the `SystemFontMetrics` on the CI environment and on my local machine behave differently.

Now I was able to implement a workaround that uses only the `IndexedFontMetrics` (luckily these inner classes are `public` and `static`), and this fixed the tests. However, it would be great if I could get rid of this extra code and use an appropriate factory method in `SimpleFontMetrics` instead.

Thanks for this library! 🙂

**Comment by ggrandes** [comment]
I will appreciate the feedback!

**Comment by obecker** [comment]
Thank you! This simplifies my code significantly. 😄
